In [4]:
import os
import numpy as np
import matplotlib

In [11]:
from matplotlib import pyplot as plt

ImportError: cannot import name 'style' from 'matplotlib' (C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py)

In [6]:
import scipy as sio

In [7]:
import sys

In [8]:
import open3d as o3d

In [32]:
plytest = o3d.io.read_point_cloud("testMeshes/model_25.ply")
print(plytest)

geometry::PointCloud with 6449 points.


In [33]:
print(np.asarray(plytest.points))
o3d.visualization.draw_geometries([plytest])

[[   33.03763718    43.16141885  -269.76254076]
 [   24.71318596    41.23312295  -261.80963083]
 [   37.62274016    44.09175438  -272.65251792]
 ...
 [  111.4752726   -113.92549641 -1001.52027269]
 [  123.91703697   -98.76821096 -1003.52497336]
 [  153.46896595   -87.80526395 -1000.5384818 ]]


In [50]:
print("Downsample the point cloud using voxels")
downply = o3d.geometry.voxel_down_sample(plytest,voxel_size=0.05)
o3d.visualization.draw_geometries([downply])

Downsample the point cloud using voxels


In [57]:
print("Recompute the normals of the downsampled point cloud")
o3d.geometry.estimate_normals(downply, search_param = o3d.geometry.KDTreeSearchParamHybrid(radius=100.0, max_nn=30))
o3d.visualization.draw_geometries([downply])

Recompute the normals of the downsampled point cloud
